version: "3.7"

services:
  db:
    image: postgres
    build:
      context: .
      dockerfile: postgres-dockerfile
    restart: unless-stopped
    ports:
     - "0.0.0.0:5432:5432"
    volumes:
      - ./db_home:/var/lib/postgresql/data
